/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import DAO.EleicaoDAO;
import Model.Eleicao;
import java.text.ParseException;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author victorPC
 */
public class ViewCadastroEleicao extends javax.swing.JFrame {
    private static final ViewCadastroEleicao INSTANCIA = new ViewCadastroEleicao();
    private boolean editar;
    private int id_edicao;
    /**
     * Creates new form frCadastroEleicao
     */
    
    private ViewCadastroEleicao() {
        initComponents();
        setModoCriacao();
        try{
            MaskFormatter maskDia = new MaskFormatter("##/##/####");
            
            maskDia.install(this.ftxtData);
        }catch(ParseException ex){
        }
    }
    
    public static ViewCadastroEleicao getInstancia(){
        return INSTANCIA;
    }   
    
    public void setModoCriacao(){
        editar = false;
        id_edicao = -1;
        this.limpaCampos();
    }
    
    public void setModoEdicao(Eleicao eleicao){
        editar = true;
        id_edicao = eleicao.getIdEleicao();
        this.txtCargo.setText(eleicao.getCargo());
        this.txtRegiao.setText(eleicao.getRegiao());
        this.ftxtData.setText(eleicao.getDataEleicao());
        this.txtTurno.setText(eleicao.getTurno());
    }
    
    public boolean verificaData(String data){
        if(data.length()!=10)
            return false;
        String[] partes = data.split("/");  
        Calendar cal = Calendar.getInstance();
        int anoAtual = cal.get(Calendar.YEAR); 
        int ano = Integer.parseInt(partes[2]);
        if(ano < anoAtual)
            return false;
        int mesAtual = cal.get(Calendar.MONTH)+1; 
        int mes = Integer.parseInt(partes[1]);
        if(mes < 1 || mes > 12)
            return false;
        if(ano == anoAtual && mes < mesAtual)
            return false;
        int dia = Integer.parseInt(partes[0]);
        int diaAtual = cal.get(Calendar.DATE);
        if(dia < 1 || dia > 31)
            return false;
        if(dia <= diaAtual && mes == mesAtual && ano == anoAtual)
            return false; 
        if(mes == 4 || mes == 6 || mes == 9 || mes == 11)
            if(dia > 30)
                return false;
        if(mes == 2){
            if(dia > 29)
                return false;
            else if(dia == 29 )
                if(!((ano % 400 == 0) || ((ano % 4 == 0) && (ano % 100 != 0))))
                    return false;
        }
        return true;
    }
    
    public void limpaCampos(){
        this.ftxtData.setText("");
        this.txtCargo.setText("");
        this.txtRegiao.setText("");
        this.txtTurno.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblTurno = new javax.swing.JLabel();
        btnConfirmar = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        lblCargo = new javax.swing.JLabel();
        txtCargo = new javax.swing.JTextField();
        lblRegiao = new javax.swing.JLabel();
        txtRegiao = new javax.swing.JTextField();
        lblData = new javax.swing.JLabel();
        ftxtData = new javax.swing.JFormattedTextField();
        txtTurno = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SimulaEleicao");

        lblTitulo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblTitulo.setText("Cadatrar eleição para o sistema:");

        lblTurno.setText("Turno:");

        btnConfirmar.setText("Confirmar ");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        lblCargo.setText("Cargo:");

        txtCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCargoActionPerformed(evt);
            }
        });

        lblRegiao.setText("Região");

        txtRegiao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRegiaoActionPerformed(evt);
            }
        });

        lblData.setText("Data da eleição:");

        ftxtData.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        txtTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTurnoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTurno)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTurno)
                            .addComponent(lblCargo)
                            .addComponent(lblRegiao)
                            .addComponent(lblData)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtCargo, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtRegiao, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnConfirmar, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)))
                            .addComponent(ftxtData, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCargo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblRegiao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtRegiao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblData)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ftxtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTurno)
                .addGap(1, 1, 1)
                .addComponent(txtTurno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnConfirmar)
                    .addComponent(btnVoltar))
                .addGap(46, 46, 46))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    public boolean validaCampos(){
        String cargo = this.txtCargo.getText();
        cargo = cargo.replace(" ", "");
        String regiao = this.txtRegiao.getText();
        regiao = regiao.replace(" ", "");
        String dia = this.ftxtData.getText();
        dia = dia.replace(" ", "");
        String turno = this.txtTurno.getText();
        turno = turno.replace(" ", "");
        if(cargo.equals("")){
            JOptionPane.showMessageDialog(null, "O campo cargo não deve ficar em branco!","Erro!", 2);
            return false;
        }
        if(regiao.equals("")){
            JOptionPane.showMessageDialog(null, "O campo regiao não deve ficar em branco!","Erro!", 2);
            return false;
        }
        if(dia.equals("//") ){
            JOptionPane.showMessageDialog(null, "O campo dia da eleição: não deve ficar em branco!","Erro!", 2);
            return false;
        }
        if(turno.equals("")){
            JOptionPane.showMessageDialog(null, "O campo turno não deve ficar em branco!","Erro!", 2);
            return false;
        }
        if(!cargo.matches("[A-Za-záàâãéèêíïóôõöúçñÁÀÂÃÉÈÍÏÓÔÕÖÚÇÑ]{3,}")){
            JOptionPane.showMessageDialog(null, "Cargo inválido!","Erro!", 2);
            return false;
        }
        if(!regiao.matches("[A-Za-záàâãéèêíïóôõöúçñÁÀÂÃÉÈÍÏÓÔÕÖÚÇÑ]{2,}")){
            JOptionPane.showMessageDialog(null, "regiao inválido!","Erro!", 2);
            return false;
        }
        if(!verificaData(dia)){
            JOptionPane.showMessageDialog(null, "Data inválida!","Erro!", 2);
            return false;
        }
        return true;
    }
    
    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        if(!this.validaCampos())
            return;
        Eleicao eleicao = new Eleicao();
        eleicao.setCargo(this.txtCargo.getText());
        eleicao.setDataEleicao(this.ftxtData.getText());
        eleicao.setRegiao(this.txtRegiao.getText());
        eleicao.setTurno(this.txtTurno.getText());
        EleicaoDAO eleicaoDAO = EleicaoDAO.getInstancia();
        if(editar){
            eleicao.setIdEleicao(id_edicao);
            if(eleicaoDAO.altera(eleicao)){
                ViewCRUDEleicao viewCRUDEleicao = ViewCRUDEleicao.getInstancia();
                viewCRUDEleicao.preencheTabela();
                JOptionPane.showMessageDialog(null,"Cadastro alterado com sucesso.","Sucesso!", 1);
                this.dispose();
                viewCRUDEleicao.setVisible(true);
            }
        }
        else
            if(eleicaoDAO.adiciona(eleicao)){
                this.limpaCampos();
                Object[] options = {"Sim", "Não"};
                if(JOptionPane.showOptionDialog(null, "Cadastro realizado com sucesso! Deseja realizar outro cadastro?","Sucesso", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, options, options[0]) == 0)
                    return;
                else{
                    this.dispose();
                    ViewCRUDEleicao viewCRUDEleicao = ViewCRUDEleicao.getInstancia();
                    viewCRUDEleicao.preencheTabela();
                    viewCRUDEleicao.setVisible(true);
                }
            }
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        this.dispose();
        ViewCRUDEleicao viewCRUDEleicao = ViewCRUDEleicao.getInstancia();
        viewCRUDEleicao.preencheTabela();
        viewCRUDEleicao.setVisible(true);
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void txtCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCargoActionPerformed

    private void txtRegiaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRegiaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRegiaoActionPerformed

    private void txtTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTurnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTurnoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JFormattedTextField ftxtData;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCargo;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblRegiao;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTurno;
    private javax.swing.JTextField txtCargo;
    private javax.swing.JTextField txtRegiao;
    private javax.swing.JTextField txtTurno;
    // End of variables declaration//GEN-END:variables
}
