/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author victorPC
 */
public class ViewDebug extends javax.swing.JFrame {
    private static final ViewDebug INSTANCIA = new ViewDebug();
    
    /**
     * Creates new form frPrincipal
     */
    private ViewDebug() {
        initComponents();
    }
    
    public static ViewDebug getInstancia(){
        return INSTANCIA;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCadastrarEleitor = new javax.swing.JButton();
        btnCadastrarPartido = new javax.swing.JButton();
        btnCRUDEleicao = new javax.swing.JButton();
        btnCadastrarCandidato = new javax.swing.JButton();
        lblTestes = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Debug Urna");
        setLocation(new java.awt.Point(0, 0));

        btnCadastrarEleitor.setText("Testar Cadastrar Eleitor");
        btnCadastrarEleitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarEleitorActionPerformed(evt);
            }
        });

        btnCadastrarPartido.setText("Testar CRUD Partido");
        btnCadastrarPartido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarPartidoActionPerformed(evt);
            }
        });

        btnCRUDEleicao.setText("Testar CRUD Eleição");
        btnCRUDEleicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCRUDEleicaoActionPerformed(evt);
            }
        });

        btnCadastrarCandidato.setText("Testar CRUD Partidario");
        btnCadastrarCandidato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarCandidatoActionPerformed(evt);
            }
        });

        lblTestes.setText("Tela de debug para testes:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnCadastrarCandidato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCRUDEleicao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCadastrarPartido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCadastrarEleitor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lblTestes))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTestes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCadastrarEleitor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCadastrarPartido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCRUDEleicao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCadastrarCandidato)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCRUDEleicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCRUDEleicaoActionPerformed
        this.dispose();
        ViewCRUDEleicao viewCRUDEleicao = ViewCRUDEleicao.getInstancia();
        viewCRUDEleicao.setVisible(true);
    }//GEN-LAST:event_btnCRUDEleicaoActionPerformed

    private void btnCadastrarEleitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarEleitorActionPerformed
        this.dispose();
        ViewCadastroEleitor viewCadastroEleitor = ViewCadastroEleitor.getInstancia();
        viewCadastroEleitor.setVisible(true);
    }//GEN-LAST:event_btnCadastrarEleitorActionPerformed

    private void btnCadastrarPartidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarPartidoActionPerformed
        this.dispose();
        ViewCRUDPartido viewCRUDPartido = ViewCRUDPartido.getInstancia();
        viewCRUDPartido.setVisible(true);
    }//GEN-LAST:event_btnCadastrarPartidoActionPerformed

    private void btnCadastrarCandidatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarCandidatoActionPerformed
        this.dispose();
        ViewCRUDPartidario viewCRUDPartidario = ViewCRUDPartidario.getInstancia();
        viewCRUDPartidario.setVisible(true);
    }//GEN-LAST:event_btnCadastrarCandidatoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCRUDEleicao;
    private javax.swing.JButton btnCadastrarCandidato;
    private javax.swing.JButton btnCadastrarEleitor;
    private javax.swing.JButton btnCadastrarPartido;
    private javax.swing.JLabel lblTestes;
    // End of variables declaration//GEN-END:variables
}
