/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import classes.Persistencia;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author victorPC
 */
public class frCadastroEleitor extends javax.swing.JFrame {

    /**
     * Creates new form frCadastroEleitor
     */
    public frCadastroEleitor() {
        initComponents();
        
        try{
            MaskFormatter maskNascimento = new MaskFormatter("##/##/####");
            MaskFormatter maskCPF = new MaskFormatter("###.###.###.##");
            MaskFormatter maskTitulo = new MaskFormatter("#### #### ####");
            
            maskNascimento.install(this.ftxtNascimento);
            maskCPF.install(this.ftxtCPF);
            maskTitulo.install(this.fxtxTituloEleitor);
        }catch(ParseException ex){
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBarra1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblNascimento = new javax.swing.JLabel();
        lblCPF = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        ftxtNascimento = new javax.swing.JFormattedTextField();
        ftxtCPF = new javax.swing.JFormattedTextField();
        fxtxTituloEleitor = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Eleiçao online");

        jLabel1.setText("Cadastro eleitoral:");

        lblNome.setText("Nome completo:");

        lblNascimento.setText("Nascimento:");

        lblCPF.setText("CPF:");

        lblTitulo.setText("Título de eleitor:");

        jButton1.setText("Canlelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Confirmar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout lblBarra1Layout = new javax.swing.GroupLayout(lblBarra1);
        lblBarra1.setLayout(lblBarra1Layout);
        lblBarra1Layout.setHorizontalGroup(
            lblBarra1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblBarra1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(lblBarra1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fxtxTituloEleitor)
                    .addGroup(lblBarra1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ftxtCPF)
                    .addComponent(txtNome)
                    .addGroup(lblBarra1Layout.createSequentialGroup()
                        .addGroup(lblBarra1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(lblNome)
                            .addComponent(lblCPF)
                            .addComponent(lblTitulo)
                            .addComponent(lblNascimento)
                            .addComponent(ftxtNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        lblBarra1Layout.setVerticalGroup(
            lblBarra1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblBarra1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNascimento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ftxtNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCPF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ftxtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fxtxTituloEleitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(lblBarra1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblBarra1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBarra1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public boolean validarCPF(String CPF){
        return true;
    }
    
    public boolean validarTitulo(String CPF){
        return true;
    }
    
    public boolean verificaData(String data){
        String[] partes = data.split("/");  
        Date d=new Date();          
        int anoAtual = 1900 + d.getYear();  
        int ano = Integer.parseInt(partes[2]);
        if(ano < 1900 || ano > anoAtual-18)
            return false;
        int mes = Integer.parseInt(partes[1]);
        if(mes < 1 || mes > 12)
            return false;
        int dia = Integer.parseInt(partes[0]);
        if(mes == 2)
            if(dia > 29)
                return false;
        if(mes == 4 || mes == 6 || mes == 9 || mes == 11)
            if(dia > 30)
                return false;
        if(dia < 1)
            return false;
        return true;
    }
    
    public boolean validaCampos(){
        String nome = this.txtNome.getText();
        nome = nome.replace(" ", "");
        String nascimento = this.ftxtNascimento.getText();
        nascimento = nascimento.replace(" ", "");
        String CPF = this.ftxtCPF.getText();
        CPF = CPF.replace(" ", "");
        String titulo = this.fxtxTituloEleitor.getText();
        titulo = titulo.replace(" ", "");
        if(nome.equals("")){
            JOptionPane.showMessageDialog(null, "O campo nome não deve ficar em branco!","Erro!", 2);
            return false;
        }
        if(nascimento.equals("//") ){
            JOptionPane.showMessageDialog(null, "O campo nascimento não deve ficar em branco!","Erro!", 2);
            return false;
        }
        if(CPF.equals("...")){
            JOptionPane.showMessageDialog(null, "O CPF não deve ficar em branco!","Erro!", 2);
            return false;
        }
        if(titulo.equals("")){
            JOptionPane.showMessageDialog(null, "O titulo não deve ficar em branco!","Erro!!", 2);
            return false;
        }
        
        if(!nome.matches("[A-Za-z]{3,}")){
            JOptionPane.showMessageDialog(null, "Nome inválido!","Erro!", 2);
            return false;
        }
        if(nascimento.length()!=10 || !verificaData(nascimento)){
            JOptionPane.showMessageDialog(null, "Data de nascimento inválida!","Erro!", 2);
            return false;
        }
        if(CPF.length()!=14){
            JOptionPane.showMessageDialog(null, "CPF inválido!","Erro!", 2);
            return false;
        }
        if(titulo.length()!=12){
            JOptionPane.showMessageDialog(null, "Título inválido!","Erro!", 2);
            return false;
        }
        validarCPF(CPF);
        validarCPF(titulo);
        return true;
    }
    
    public void limpaCampos(){
        this.ftxtCPF.setText("");
        this.ftxtNascimento.setText("");
        this.fxtxTituloEleitor.setText("");
        this.txtNome.setText("");
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        new frDebug().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(!this.validaCampos())
            return;
        PreparedStatement ps = null;
        try{
            ps = Persistencia.conexao().prepareStatement("Insert into Eleitor (nome, nascimento, CPF, titulo) values ('"+this.txtNome.getText()+"','"
            +this.ftxtNascimento.getText()+"','"+this.ftxtCPF.getText()+"','"+this.fxtxTituloEleitor.getText()+"');");            
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null,"Cadastro Realizado com sucesso.","Sucesso!", 1);          
        }
        catch(SQLException ex){
            JOptionPane.showMessageDialog(null,"Não foi possível conectar ao banco de dados.","Erro!", 2);           
        }
        this.limpaCampos();
    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField ftxtCPF;
    private javax.swing.JFormattedTextField ftxtNascimento;
    private javax.swing.JFormattedTextField fxtxTituloEleitor;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel lblBarra1;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblNascimento;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
