/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ifsudestemg.View;

import ifsudestemg.Controller.EleicaoController;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author victorPC
 */

public class ViewCRUDEleicao extends javax.swing.JFrame {
    private EleicaoController eleicaoController;
    private DefaultTableModel model;
    private javax.swing.JFrame origem; 
    

    @Override
    public void setVisible(boolean bln){
        super.setVisible(bln);
        preencheTabela();
    }

    public ViewCRUDEleicao(javax.swing.JFrame origem, EleicaoController eleicaoController) {
        this.origem = origem;
        this.eleicaoController = eleicaoController;
        initComponents();
    }    
    
    public void preencheTabela(){
        String[] colunas = {"ID","Cargo","Região","Data","Turno"}; 
        model = new DefaultTableModel(colunas,0);
        Object[][] dados;
        try {
            dados = eleicaoController.retornaDados();
            for (Object[] dado : dados) {
                Object[] linha = {dado[0], dado[1], dado[2], dado[3], dado[4]};
                model.addRow(linha);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,"Erro ao consultar os registros, tente novamente mais tarde!","Erro!", 0);
        } catch (ClassNotFoundException ex) {
           JOptionPane.showMessageDialog(this,"Driver do banco de dados inexistente, comunique o administrador do sistema!","Erro!", 0);
        }
        this.tblEleicoes.setModel(model);
        this.tblEleicoes.removeColumn(this.tblEleicoes.getColumnModel().getColumn(0));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEleicoes = new javax.swing.JTable();
        lblEleicoesExistentes = new javax.swing.JLabel();
        btnNovo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnPartidos = new javax.swing.JButton();
        btnCandidatos = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Eleição Online");

        tblEleicoes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblEleicoes);

        lblEleicoesExistentes.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblEleicoesExistentes.setText("Lista de eleições existentes:");

        btnNovo.setText("Nova eleição");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar eleição selecionada");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnPartidos.setText("Alterar partidos da da eleição");
        btnPartidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPartidosActionPerformed(evt);
            }
        });

        btnCandidatos.setText("Alterar candidatos da eleição");
        btnCandidatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCandidatosActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir eleição selecionada");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEleicoesExistentes)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPartidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCandidatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVoltar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(6, 6, 6))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEleicoesExistentes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnNovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPartidos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCandidatos)
                        .addGap(5, 5, 5)
                        .addComponent(btnExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnVoltar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnCandidatos, btnEditar, btnExcluir, btnNovo, btnPartidos, btnVoltar});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        this.setVisible(false);
        ViewCadastroEleicao viewCadastroEleicao = new ViewCadastroEleicao(this,eleicaoController);
        viewCadastroEleicao.setVisible(true);
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        int indice = this.tblEleicoes.getSelectedRow();
        if(indice !=-1){
            ViewCadastroEleicao viewCadastroEleicao = new ViewCadastroEleicao(this,eleicaoController,(int) model.getValueAt(indice, 0),(""+model.getValueAt(indice, 1)),(""+model.getValueAt(indice, 2)),(""+model.getValueAt(indice, 3)),(""+model.getValueAt(indice, 4)));
            this.setVisible(false);
            viewCadastroEleicao.setVisible(true);
        }
        else
            JOptionPane.showMessageDialog(this,"Aviso, selecione uma eleição para ser editada!","Aviso!", 2);    
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int indice = this.tblEleicoes.getSelectedRow();
        if(indice !=-1){
            Object[] options = {"Confirmar", "Cancelar"};
            if(JOptionPane.showOptionDialog(null, "Deseja mesmo excluir a eleição para "+(""+model.getValueAt(indice, 1)).toLowerCase()+","+(""+model.getValueAt(indice, 2)).toLowerCase()+" turno, planejada para o dia "
            +(""+model.getValueAt(indice, 3))+" na região de "+(""+model.getValueAt(indice, 4))+"?","Aviso", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, options, options[1]) == 0)
            {
                try{
                    eleicaoController.excluirPorId((int) model.getValueAt(indice, 0));
                    preencheTabela();
                    JOptionPane.showMessageDialog(this,"Deletado com sucesso!","Sucesso!", 1);
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(this,"Erro ao excluir o registro, tente novamente mais tarde!","Erro!", 0);
                } catch (ClassNotFoundException ex) {
                   JOptionPane.showMessageDialog(this,"Driver do banco de dados inexistente, comunique o administrador do sistema!","Erro!", 0);
                }  
            }
        }
        else
            JOptionPane.showMessageDialog(this,"Aviso, selecione uma eleição para ser excluida!","Aviso!", 2);    
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        this.dispose();
        origem.setVisible(true);        
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnPartidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPartidosActionPerformed
        int indice = this.tblEleicoes.getSelectedRow();
        if(indice !=-1){    
            ViewAtribuirLegenda viewAtribuirLegenda = new ViewAtribuirLegenda(this,(int) this.model.getValueAt(indice, 0));
            viewAtribuirLegenda.setVisible(true);
            this.dispose();
        }
        else
            JOptionPane.showMessageDialog(this,"Aviso, selecione uma eleição para selecionar seus partidos!","Aviso!", 2);
    }//GEN-LAST:event_btnPartidosActionPerformed

    private void btnCandidatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCandidatosActionPerformed
        int indice = this.tblEleicoes.getSelectedRow();
        if(indice !=-1){    
            ViewAtribuirCandidato viewAtribuirCandidato = new ViewAtribuirCandidato(this, (int) this.model.getValueAt(indice, 0));
            viewAtribuirCandidato.setVisible(true);
            this.dispose();
        }
        else
            JOptionPane.showMessageDialog(this,"Aviso, selecione uma eleição para selecionar seus partidos!","Aviso!", 2);
    }//GEN-LAST:event_btnCandidatosActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCandidatos;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPartidos;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEleicoesExistentes;
    private javax.swing.JTable tblEleicoes;
    // End of variables declaration//GEN-END:variables
}
