/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ifsudestemg.View;

import ifsudestemg.Controller.PartidarioController;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author victorPC
 */
public class ViewCadastroPartidario extends javax.swing.JFrame {
    private PartidarioController partidarioController;
    private int idEdicao;
    
    /**
     * Creates new form frCadastroCanditado
     */
    public ViewCadastroPartidario(PartidarioController partidarioController) {
        this.partidarioController = partidarioController;
        initComponents();
        idEdicao = -1;
        aplicaMascara();
    }
    
    private void aplicaMascara(){
        try{
            MaskFormatter maskCPF = new MaskFormatter("###.###.###.##");
            MaskFormatter maskNumero = new MaskFormatter("##");
            
            maskCPF.install(this.ftxtCPF);
            maskNumero.install(this.ftxtNumero);
        }catch(ParseException ex){
        }
    }
    
    public ViewCadastroPartidario(PartidarioController partidarioController, int idPartidario, String cpf, String numero, String cargoNoPartido) {
        this.partidarioController = partidarioController;
        initComponents();
        aplicaMascara();        
        idEdicao = idPartidario;
        this.ftxtCPF.setText(cpf);
        this.ftxtCPF.setEditable(false);
        this.ftxtNumero.setText(numero);
        this.txtCargo.setText(cargoNoPartido);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblNumero = new javax.swing.JLabel();
        lblCargo = new javax.swing.JLabel();
        txtCargo = new javax.swing.JTextField();
        btnConfirmar = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        lblCPF = new javax.swing.JLabel();
        ftxtCPF = new javax.swing.JFormattedTextField();
        ftxtNumero = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Eleiçao online");

        lblTitulo.setText("Cadastrar partidário:");

        lblNumero.setText("Número do partido:");

        lblCargo.setText("Cargo no partido:");

        txtCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCargoActionPerformed(evt);
            }
        });

        btnConfirmar.setText("Confirmar");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        lblCPF.setText("CPF:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitulo)
                            .addComponent(lblNumero)
                            .addComponent(lblCargo))
                        .addContainerGap(98, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtCargo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(lblCPF))
                            .addComponent(ftxtCPF)
                            .addComponent(ftxtNumero))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCPF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ftxtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNumero)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ftxtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCargo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVoltar)
                    .addComponent(btnConfirmar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
   
    
    public boolean validaCampos(){
        String cpf = this.ftxtCPF.getText();
        cpf = cpf.replace(" ", "");
        String numero = this.ftxtNumero.getText();
        numero = numero.replace(" ", "");
        String cargo = this.txtCargo.getText();
        cargo = cargo.replace(" ", "");
        
        if(cpf.equals("...")){
            JOptionPane.showMessageDialog(this, "O cpf não deve ficar em branco!","Erro!", 2);
            return false;
        }
        if(numero.equals("")){
            JOptionPane.showMessageDialog(this, "O campo número não deve ficar em branco!","Erro!", 2);
            return false;
        }
        if(cargo.equals("")){
            JOptionPane.showMessageDialog(this, "O cargo não deve ficar em branco!","Erro!!", 2);
            return false;
        }
        if(!partidarioController.validarCPF(cpf)){
            JOptionPane.showMessageDialog(this, "cpf inválido!","Erro!", 2);
            return false;
        }
        if(!numero.matches("[0-9]{2,5}")){
            JOptionPane.showMessageDialog(this, "Número inválido!","Erro!", 2);
            return false;
        }
        if(!cargo.matches("[A-Za-záàâãéèêíïóôõöúçñÁÀÂÃÉÈÍÏÓÔÕÖÚÇÑ]{3,}")){
            JOptionPane.showMessageDialog(this, "Cargo inválido!","Erro!!", 2);
            return false;
        }
        return true;
    }
    
    private void limpaCampos() {
        this.ftxtCPF.setText("");
        this.ftxtNumero.setText("");
        this.txtCargo.setText("");
    }
    
    private void txtCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCargoActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        this.dispose();
        ViewCRUDPartidario viewCRUDPartidario = new ViewCRUDPartidario(partidarioController);
        viewCRUDPartidario.preencheTabela();
        viewCRUDPartidario.setVisible(true);
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        if(!this.validaCampos())
            return;
        if(idEdicao==-1){
            try {
                partidarioController.adicionar(this.ftxtCPF.getText(), Integer.parseInt(this.ftxtNumero.getText()), this.txtCargo.getText());
                this.limpaCampos();
                Object[] options = {"Sim", "Não"};
                if(JOptionPane.showOptionDialog(null, "Cadastro realizado com sucesso! Deseja realizar outro cadastro?","Sucesso", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, options, options[0]) == 0)
                    return;
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this,"Erro ao adicionar o registro, tente novamente mais tarde!","Erro!", 0);
                return;
            }catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this,"Eleitor com o CPF digitado inexistente!","Erro!", 2);
                return;
            } catch (NegativeArraySizeException ex) {
                JOptionPane.showMessageDialog(this,"Partidário com esse CPF já existe!","Erro!", 2);
                return;
            } catch (ArithmeticException ex) {
                JOptionPane.showMessageDialog(this,"Partido com o número digitado inexistente!","Erro!", 2);
                return;
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(ViewCadastroPartidario.class.getName()).log(Level.SEVERE, null, ex);
                return;
            } 
        }
        else{
            try {
                partidarioController.alterarPorId(idEdicao, Integer.parseInt(this.ftxtNumero.getText()), this.txtCargo.getText());
                JOptionPane.showMessageDialog(this,"Cadastro alterado com sucesso.","Sucesso!", 1);
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this,"Erro ao alterar o registro, tente novamente mais tarde!","Erro!", 0);
                return;
            }catch (ArithmeticException ex) {
                JOptionPane.showMessageDialog(this,"Partido com o número digitado inexistente!","Erro!", 2);
                return;
            }catch (ClassNotFoundException ex) {
                Logger.getLogger(ViewCadastroPartidario.class.getName()).log(Level.SEVERE, null, ex);
                return;
            } 
        }
        this.dispose();
        ViewCRUDPartidario viewCRUDPartidario = new ViewCRUDPartidario(partidarioController);
        viewCRUDPartidario.preencheTabela();
        viewCRUDPartidario.setVisible(true);
    }//GEN-LAST:event_btnConfirmarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JFormattedTextField ftxtCPF;
    private javax.swing.JFormattedTextField ftxtNumero;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblCargo;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtCargo;
    // End of variables declaration//GEN-END:variables

}
