/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ifsudestemg.View;

import ifsudestemg.Controller.EleitorController;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author victorPC
 */
public class ViewAreaInternaEleitor extends javax.swing.JFrame {
    EleitorController eleitorController = new EleitorController();
    private int idEleitor;
    /**
     * Creates new form ViewAreaInternaEleitor
     */
    public ViewAreaInternaEleitor(String cpf) throws ClassNotFoundException, SQLException {
        initComponents();
        EleitorController eleitorController = new EleitorController();
        idEleitor = eleitorController.consultarID(cpf);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVotarEleicao = new javax.swing.JButton();
        btnAlterarCadastro = new javax.swing.JButton();
        lblTextoBoasVindas = new javax.swing.JLabel();
        btnSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Urna Online");

        btnVotarEleicao.setText("Votar em eleição");
        btnVotarEleicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVotarEleicaoActionPerformed(evt);
            }
        });

        btnAlterarCadastro.setText("Alterar dados cadastrais");
        btnAlterarCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarCadastroActionPerformed(evt);
            }
        });

        lblTextoBoasVindas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTextoBoasVindas.setText("Bem vindo!");

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnAlterarCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnVotarEleicao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTextoBoasVindas, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnSair, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTextoBoasVindas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVotarEleicao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAlterarCadastro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSair)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVotarEleicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVotarEleicaoActionPerformed
        this.setVisible(false);
        new ViewVotar(this,idEleitor).setVisible(true);
    }//GEN-LAST:event_btnVotarEleicaoActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        this.dispose();
        ViewRealizarLogin viewRealizarLogin = new ViewRealizarLogin();
        viewRealizarLogin.setVisible(true);
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnAlterarCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarCadastroActionPerformed
        this.setVisible(false);        
        try {
            new ViewCadastroEleitor(this,eleitorController,idEleitor).setVisible(true);
        } catch (ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(this,"Driver do banco de dados não encontrado, contate o administrador do banco!","Erro!", 0);
        } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this,"Não foi possível se conectar ao banco de dados, tente novamente mais tarde!","Erro!", 0);
        }
    }//GEN-LAST:event_btnAlterarCadastroActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterarCadastro;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnVotarEleicao;
    private javax.swing.JLabel lblTextoBoasVindas;
    // End of variables declaration//GEN-END:variables
}
