/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ifsudestemg.View;

import ifsudestemg.Controller.EleicaoController;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author victorPC
 */
public class ViewCadastroEleicao extends javax.swing.JFrame {
    EleicaoController eleicaoController;
    private int idEdicao;
    /**
     * Creates new form frCadastroEleicao
     */
    
    public ViewCadastroEleicao(EleicaoController eleicaoController) {
        this.eleicaoController = eleicaoController;
        initComponents();
        aplicaMascara();
        idEdicao = -1;
    }
    
    private void aplicaMascara(){
        try{
            MaskFormatter maskDia = new MaskFormatter("##/##/####");
            
            maskDia.install(this.ftxtData);
        }catch(ParseException ex){
        }
    }
    
    
    public ViewCadastroEleicao(EleicaoController eleicaoController,int idEleicao, String cargo, String regiao, String dataEleicao, String turno) {
        this.eleicaoController = eleicaoController;
        initComponents();
        aplicaMascara();
        idEdicao = idEleicao;
        this.txtCargo.setText(cargo);
        this.txtRegiao.setText(regiao);
        this.ftxtData.setText(dataEleicao);
        this.txtTurno.setText(turno);
    }
    
    public void limpaCampos(){
        this.ftxtData.setText("");
        this.txtCargo.setText("");
        this.txtRegiao.setText("");
        this.txtTurno.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblTurno = new javax.swing.JLabel();
        btnConfirmar = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        lblCargo = new javax.swing.JLabel();
        txtCargo = new javax.swing.JTextField();
        lblRegiao = new javax.swing.JLabel();
        txtRegiao = new javax.swing.JTextField();
        lblData = new javax.swing.JLabel();
        ftxtData = new javax.swing.JFormattedTextField();
        txtTurno = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SimulaEleicao");

        lblTitulo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblTitulo.setText("Cadatrar eleição para o sistema:");

        lblTurno.setText("Turno:");

        btnConfirmar.setText("Confirmar ");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        lblCargo.setText("Cargo:");

        txtCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCargoActionPerformed(evt);
            }
        });

        lblRegiao.setText("Região");

        txtRegiao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRegiaoActionPerformed(evt);
            }
        });

        lblData.setText("Data da eleição:");

        ftxtData.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        txtTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTurnoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTurno)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTurno)
                            .addComponent(lblCargo)
                            .addComponent(lblRegiao)
                            .addComponent(lblData)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtCargo, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtRegiao, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnConfirmar, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)))
                            .addComponent(ftxtData, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCargo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblRegiao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtRegiao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblData)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ftxtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTurno)
                .addGap(1, 1, 1)
                .addComponent(txtTurno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnConfirmar)
                    .addComponent(btnVoltar))
                .addGap(46, 46, 46))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    public boolean validaCampos(){
        String cargo = this.txtCargo.getText();
        cargo = cargo.replace(" ", "");
        String regiao = this.txtRegiao.getText();
        regiao = regiao.replace(" ", "");
        String dia = this.ftxtData.getText();
        dia = dia.replace(" ", "");
        String turno = this.txtTurno.getText();
        turno = turno.replace(" ", "");
        if(cargo.equals("")){
            JOptionPane.showMessageDialog(this, "O campo cargo não deve ficar em branco!","Erro!", 2);
            return false;
        }
        if(regiao.equals("")){
            JOptionPane.showMessageDialog(this, "O campo regiao não deve ficar em branco!","Erro!", 2);
            return false;
        }
        if(dia.equals("//") ){
            JOptionPane.showMessageDialog(this, "O campo dia da eleição: não deve ficar em branco!","Erro!", 2);
            return false;
        }
        if(turno.equals("")){
            JOptionPane.showMessageDialog(this, "O campo turno não deve ficar em branco!","Erro!", 2);
            return false;
        }
        if(!cargo.matches("[A-Za-záàâãéèêíïóôõöúçñÁÀÂÃÉÈÍÏÓÔÕÖÚÇÑ]{3,}")){
            JOptionPane.showMessageDialog(this, "Cargo inválido!","Erro!", 2);
            return false;
        }
        if(!regiao.matches("[A-Za-záàâãéèêíïóôõöúçñÁÀÂÃÉÈÍÏÓÔÕÖÚÇÑ]{2,}")){
            JOptionPane.showMessageDialog(this, "regiao inválido!","Erro!", 2);
            return false;
        }
        if(!eleicaoController.validarDataEleicao(dia)){
            JOptionPane.showMessageDialog(this, "Data inválida!","Erro!", 2);
            return false;
        }
        return true;
    }
    
    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        if(!this.validaCampos())
            return;
        if(idEdicao==-1){
            try {
                eleicaoController.adicionar(this.txtCargo.getText(), this.txtRegiao.getText(), this.ftxtData.getText(), this.txtTurno.getText());
                this.limpaCampos();
                Object[] options = {"Sim", "Não"};
                if(JOptionPane.showOptionDialog(null, "Cadastro realizado com sucesso! Deseja realizar outro cadastro?","Sucesso", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, options, options[0]) == 0)
                    return;
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this,"Erro ao adicionar o registro, tente novamente mais tarde!","Erro!", 0);
                return;
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(ViewCadastroEleicao.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else{
            try {
                eleicaoController.alterarPorId(idEdicao, this.txtCargo.getText(), this.txtRegiao.getText(), this.ftxtData.getText(), this.txtTurno.getText());
                JOptionPane.showMessageDialog(this,"Cadastro alterado com sucesso.","Sucesso!", 1);
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this,"Erro ao alterar o registro, tente novamente mais tarde!","Erro!", 0);
                return;
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(ViewCadastroEleicao.class.getName()).log(Level.SEVERE, null, ex);
            }   
        }
        this.dispose();
        ViewCRUDEleicao viewCRUDEleicao = new ViewCRUDEleicao(eleicaoController);
        viewCRUDEleicao.preencheTabela();
        viewCRUDEleicao.setVisible(true);
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        this.dispose();
        ViewCRUDEleicao viewCRUDEleicao = new ViewCRUDEleicao(eleicaoController);
        viewCRUDEleicao.preencheTabela();
        viewCRUDEleicao.setVisible(true);
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void txtCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCargoActionPerformed

    private void txtRegiaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRegiaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRegiaoActionPerformed

    private void txtTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTurnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTurnoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JFormattedTextField ftxtData;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCargo;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblRegiao;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTurno;
    private javax.swing.JTextField txtCargo;
    private javax.swing.JTextField txtRegiao;
    private javax.swing.JTextField txtTurno;
    // End of variables declaration//GEN-END:variables
}
