/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ifsudestemg.View;

import ifsudestemg.Controller.EleitorController;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author victorPC
 */
public class ViewCadastroEleitor extends javax.swing.JFrame {
        EleitorController eleitorController;

    /**
     * Creates new form frCadastroEleitor
     */
    public ViewCadastroEleitor(EleitorController eleitorController) {
        initComponents();
        aplicaMascara();
        this.eleitorController = eleitorController;
    }
    
    private void aplicaMascara(){
        try{
            MaskFormatter maskNascimento = new MaskFormatter("##/##/####");
            MaskFormatter maskCPF = new MaskFormatter("###.###.###.##");
            MaskFormatter maskTitulo = new MaskFormatter("#############");
            
            maskNascimento.install(this.ftxtNascimento);
            maskCPF.install(this.ftxtCPF);
            maskTitulo.install(this.fxtxTituloEleitor);
        }catch(ParseException ex){
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBarra1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblNascimento = new javax.swing.JLabel();
        lblCPF = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();
        btnConfirmar = new javax.swing.JButton();
        ftxtNascimento = new javax.swing.JFormattedTextField();
        ftxtCPF = new javax.swing.JFormattedTextField();
        fxtxTituloEleitor = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Eleiçao online");

        jLabel1.setText("Cadastro eleitoral:");

        lblNome.setText("Nome completo:");

        lblNascimento.setText("Nascimento:");

        lblCPF.setText("CPF:");

        lblTitulo.setText("Título de eleitor:");

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        btnConfirmar.setText("Confirmar");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        ftxtNascimento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ftxtNascimentoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout lblBarra1Layout = new javax.swing.GroupLayout(lblBarra1);
        lblBarra1.setLayout(lblBarra1Layout);
        lblBarra1Layout.setHorizontalGroup(
            lblBarra1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblBarra1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(lblBarra1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fxtxTituloEleitor)
                    .addGroup(lblBarra1Layout.createSequentialGroup()
                        .addComponent(btnVoltar, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ftxtCPF)
                    .addComponent(txtNome)
                    .addGroup(lblBarra1Layout.createSequentialGroup()
                        .addGroup(lblBarra1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(lblNome)
                            .addComponent(lblCPF)
                            .addComponent(lblTitulo)
                            .addComponent(lblNascimento)
                            .addComponent(ftxtNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        lblBarra1Layout.setVerticalGroup(
            lblBarra1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblBarra1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNascimento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ftxtNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCPF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ftxtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fxtxTituloEleitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(lblBarra1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVoltar)
                    .addComponent(btnConfirmar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblBarra1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBarra1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    public boolean validaCampos(){
        String nome = this.txtNome.getText();
        nome = nome.replace(" ", "");
        String nascimento = this.ftxtNascimento.getText();
        nascimento = nascimento.replace(" ", "");
        String cpf = this.ftxtCPF.getText();
        cpf = cpf.replace(" ", "");
        String titulo = this.fxtxTituloEleitor.getText().replace(" ", "");
        if(nome.equals("")){
            JOptionPane.showMessageDialog(this, "O campo nome não deve ficar em branco!","Erro!", 2);
            return false;
        }
        if(nascimento.equals("//") ){
            JOptionPane.showMessageDialog(this, "O campo nascimento não deve ficar em branco!","Erro!", 2);
            return false;
        }
        if(cpf.equals("...")){
            JOptionPane.showMessageDialog(this, "O cpf não deve ficar em branco!","Erro!", 2);
            return false;
        }
        if(titulo.equals("")){
            JOptionPane.showMessageDialog(this, "O titulo não deve ficar em branco!","Erro!!", 2);
            return false;
        }
        
        if(!nome.matches("[A-Za-záàâãéèêíïóôõöúçñÁÀÂÃÉÈÍÏÓÔÕÖÚÇÑ]{3,}")){
            JOptionPane.showMessageDialog(this, "Nome inválido!","Erro!", 2);
            return false;
        }
        if(!eleitorController.validarNascimento(nascimento)){
            JOptionPane.showMessageDialog(this, "Data de nascimento inválida!","Erro!", 2);
            return false;
        }
        if(!eleitorController.validarCPF(cpf)){
            JOptionPane.showMessageDialog(this, "cpf inválido!","Erro!", 2);
            return false;
        }
        if(!eleitorController.validarTitulo(titulo)){
            JOptionPane.showMessageDialog(this, "Título inválido!","Erro!", 2);
            return false;
        }
        
        return true;
    }
    
    public void limpaCampos(){
        this.ftxtCPF.setText("");
        this.ftxtNascimento.setText("");
        this.fxtxTituloEleitor.setText("");
        this.txtNome.setText("");
    }
    
    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        this.dispose();
        ViewDebug viewDebug = new ViewDebug();
        viewDebug.setVisible(true);
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        if(!this.validaCampos())
            return;
        try {
            eleitorController.adicionar(this.txtNome.getText(), this.ftxtNascimento.getText(), this.ftxtCPF.getText(), this.fxtxTituloEleitor.getText());
            JOptionPane.showMessageDialog(this,"Cadastro realizado com sucesso.","Sucesso!", 1);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,"Erro ao realizar o cadastro, tente novamente mais tarde!","Erro!", 0);
        } catch (NumberFormatException ex2) {
            JOptionPane.showMessageDialog(this,"CPF já cadastrado!","Erro!", 2);
        } catch (NegativeArraySizeException ex3) {
            JOptionPane.showMessageDialog(this,"Título de eleitor já cadastrado!","Erro!", 2);
        } catch (ClassNotFoundException ex4) {
            Logger.getLogger(ViewCadastroEleitor.class.getName()).log(Level.SEVERE, null, ex4);
        }        
        this.dispose();
        ViewDebug viewDebug = new ViewDebug();
        viewDebug.setVisible(true);
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void ftxtNascimentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ftxtNascimentoMouseClicked
    }//GEN-LAST:event_ftxtNascimentoMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JFormattedTextField ftxtCPF;
    private javax.swing.JFormattedTextField ftxtNascimento;
    private javax.swing.JFormattedTextField fxtxTituloEleitor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel lblBarra1;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblNascimento;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
