/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ifsudestemg.View;

import ifsudestemg.Controller.PartidoController;
import java.sql.SQLException;
import java.text.ParseException;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author victorPC
 */
public class ViewCadastroPartido extends javax.swing.JFrame {
    private PartidoController partidoController;
    private int idEdicao;
    private javax.swing.JFrame origem;

    /** 
     * Creates new form frCadastroPartido
     */
    public ViewCadastroPartido(javax.swing.JFrame origem, PartidoController partidoController) {
        this.origem = origem;
        idEdicao = -1;
        this.partidoController = partidoController;
        initComponents();
        aplicaMascara();
    }
    
    private void aplicaMascara(){
        try{
            MaskFormatter maskNumero = new MaskFormatter("##");
            
            maskNumero.install(this.ftxtNumero);
        }catch(ParseException ex){
        }
    }
    
    public ViewCadastroPartido(javax.swing.JFrame origem, PartidoController partidoController, int id_edicao, String numero, String nome) {
        this.origem = origem;
        this.partidoController = partidoController;
        initComponents();
        aplicaMascara();        
        this.idEdicao = id_edicao;
        this.ftxtNumero.setText((""+numero));
        this.txtNome.setText(nome);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblNumero = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        btnVoltar = new javax.swing.JButton();
        btnConfirmar = new javax.swing.JButton();
        ftxtNumero = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Eleiçao online");

        jPanel1.setToolTipText("");

        lblTitulo.setText("Cadastrar novo partido:");

        lblNumero.setText("Número:");

        lblNome.setText("Nome:");

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        btnConfirmar.setText("Confirmar");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        ftxtNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftxtNumeroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTitulo)
                    .addComponent(lblNumero)
                    .addComponent(lblNome)
                    .addComponent(txtNome)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ftxtNumero))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNumero)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ftxtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVoltar)
                    .addComponent(btnConfirmar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public boolean validaCampos(){
        String numero = this.ftxtNumero.getText();
        numero = numero.replace(" ", "");
        String nome = this.txtNome.getText();
        nome = nome.replace(" ", "");
        
        if(numero.equals("")){
            JOptionPane.showMessageDialog(this, "O campo número não deve ficar em branco!","Erro!", 2);
            return false;
        }
        if(nome.equals("")){
            JOptionPane.showMessageDialog(this, "O nome não deve ficar em branco!","Erro!!", 2);
            return false;
        }
        
        if(!numero.matches("[0-9]{2,5}")){
            JOptionPane.showMessageDialog(this, "Número inválido!","Erro!", 2);
            return false;
        }
        if(!nome.matches("[A-Za-záàâãéèêîíïóôõöúçñÁÀÂÃÉÈÍÏÓÔÕÖÚÇÑÎ]{3,200}")){
            JOptionPane.showMessageDialog(this, "Nome inválido!","Erro!!", 2);
            return false;
        }
        if(Integer.parseInt(numero) < 10){
            JOptionPane.showMessageDialog(this, "Número inválido!","Erro!!", 2);
            return false; 
        }
        return true;
    }
    
    public void limpaCampos(){
        this.ftxtNumero.setText("");
        this.txtNome.setText("");
    }

    
    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        this.dispose();
        origem.setVisible(true);
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        if(!validaCampos())
            return;
        if(idEdicao==-1){
            try {
                partidoController.adicionar(Integer.parseInt(this.ftxtNumero.getText()),this.txtNome.getText());
                this.limpaCampos();
                Object[] options = {"Sim", "Não"};
                if(JOptionPane.showOptionDialog(null, "Cadastro realizado com sucesso! Deseja realizar outro cadastro?","Sucesso", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, options, options[0]) == 0)
                    return;
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this,"Erro ao adicionar o registro, tente novamente mais tarde!","Erro!", 0);
                return;
            } catch (NumberFormatException ex2) {
                JOptionPane.showMessageDialog(this,"Partido com esse número já existente!","Erro!", 2);
                return;
            } catch (NegativeArraySizeException ex3) {
                JOptionPane.showMessageDialog(this,"Partido com esse nome já existente!","Erro!", 2);
                return;
            } catch (ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(this,"A primeira e a segunda senha não conferem!","Erro!", 0);
            }    
        }
        else{
            try {
                partidoController.alterarPorId(idEdicao, Integer.parseInt(this.ftxtNumero.getText()), this.txtNome.getText());
                JOptionPane.showMessageDialog(this,"Cadastro alterado com sucesso.","Sucesso!", 1);
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this,"Erro ao alterar o registro, tente novamente mais tarde!","Erro!", 0);
                return;
            } catch (NumberFormatException ex2) {
                JOptionPane.showMessageDialog(this,"Partido com esse número já existente!","Erro!", 2);
                return;
            } catch (NegativeArraySizeException ex3) {
                JOptionPane.showMessageDialog(this,"Partido com esse nome já existente!","Erro!", 2);
                return;
            } catch (ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(this,"A primeira e a segunda senha não conferem!","Erro!", 0);
            }      
        }
        this.dispose();
        origem.setVisible(true);
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void ftxtNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftxtNumeroActionPerformed
        
    }//GEN-LAST:event_ftxtNumeroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JFormattedTextField ftxtNumero;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables

}
