/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ifsudestemg.View;

import ifsudestemg.Controller.EleicaoController;
import ifsudestemg.Controller.LegendaController;
import ifsudestemg.Controller.PartidoController;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author victorPC
 */
public class ViewAtribuirLegenda extends javax.swing.JFrame {
    private LegendaController legendaController;
    private DefaultTableModel model;
    private int idEleicao;
    private javax.swing.JFrame origem;
    
    @Override
    public void setVisible(boolean bln){
        super.setVisible(bln);
        preencheTabela();
    }
    
    /**
     * Creates new form frSelecionarPartidos
     */
    public ViewAtribuirLegenda(javax.swing.JFrame origem, int idEleicao) {
        this.origem = origem;
        initComponents();
        this.idEleicao = idEleicao;
        this.legendaController = new LegendaController();
    }    
    
    public void preencheTabela(){
        String[] colunas = {"IDP","Numero do Partido","Nome","IDL","Na eleição?"}; 
        model = new DefaultTableModel(colunas,0);
        Object[][] dados;
        try {
            dados = legendaController.retornaDados(idEleicao);
            for (Object[] dado : dados) {
                Object[] linha = {dado[0], dado[1], dado[2], dado[3], dado[4]};
                model.addRow(linha);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,"Erro ao consultar os registros, tente novamente mais tarde!","Erro!", 0);
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this,"Driver do banco de dados inexistente, comunique o administrador do sistema!","Erro!", 0);
        }
        this.tblLegendas.setModel(model);
        this.tblLegendas.removeColumn(this.tblLegendas.getColumnModel().getColumn(0));
        this.tblLegendas.removeColumn(this.tblLegendas.getColumnModel().getColumn(2));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnAdicionarRemover = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        btnCadastrar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLegendas = new javax.swing.JTable();
        lblTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Eleição Online");

        btnAdicionarRemover.setText("Adicionar");
        btnAdicionarRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarRemoverActionPerformed(evt);
            }
        });

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        btnCadastrar.setText("Cadastrar novo");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar selecionado");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAdicionarRemover, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(btnCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVoltar, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAdicionarRemover, btnCadastrar, btnEditar, btnVoltar});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(btnAdicionarRemover)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCadastrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVoltar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblLegendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblLegendas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLegendasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblLegendas);

        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTitulo.setText("Partidos cadastrados:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitulo)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 2, Short.MAX_VALUE)
                        .addComponent(lblTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarRemoverActionPerformed
        int indice = this.tblLegendas.getSelectedRow();
        if(indice !=-1){
            if(((int)model.getValueAt(indice, 3)) == -1)
                try {
                    legendaController.adicionar((int)model.getValueAt(indice, 0),idEleicao);
                    this.btnAdicionarRemover.setText("Remover");
                } catch (ClassNotFoundException ex) {
                    JOptionPane.showMessageDialog(this,"Erro ao criar a legenda partidária, tente novamente mais tarde!","Erro!", 0);
                } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,"A primeira e a segunda senha não conferem!","Erro!", 0);
            }
            else
                try {
                    legendaController.excluirPorId((int)model.getValueAt(indice, 3));
                    this.btnAdicionarRemover.setText("Adicionar");
                } catch (ClassNotFoundException ex) {
                    JOptionPane.showMessageDialog(this,"Erro ao remover a legenda partidária, tente novamente mais tarde!","Erro!", 0);
                } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,"A primeira e a segunda senha não conferem!","Erro!", 0);
                }
            this.preencheTabela();
            this.tblLegendas.setRowSelectionInterval(indice, indice);
        }
        else
            JOptionPane.showMessageDialog(this,"Aviso, selecione um partido para adicionar à eleição!","Aviso!", 2);
    }//GEN-LAST:event_btnAdicionarRemoverActionPerformed

    private void tblLegendasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLegendasMouseClicked
        int indice = this.tblLegendas.getSelectedRow();
        if(indice !=-1)
            if(((int)model.getValueAt(indice, 3))!=-1)
                this.btnAdicionarRemover.setText("Remover");
            else
                this.btnAdicionarRemover.setText("Adicionar");
    }//GEN-LAST:event_tblLegendasMouseClicked

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        this.dispose();
        origem.setVisible(true);
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        int indice = this.tblLegendas.getSelectedRow();
        if(indice !=-1){
            PartidoController partidoController = new PartidoController();
            ViewCadastroPartido viewCadastroPartido = new ViewCadastroPartido(this,partidoController,((int)model.getValueAt(indice, 0)),(""+model.getValueAt(indice, 1)),(""+model.getValueAt(indice, 2)));
            this.dispose();
            viewCadastroPartido.setVisible(true);
        }
        else
        JOptionPane.showMessageDialog(this,"Aviso, selecione um partido para ser editado!","Aviso!", 2);
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        this.dispose();
        PartidoController partidoController = new PartidoController();
        ViewCadastroPartido viewCadastroPartido = new ViewCadastroPartido(this, partidoController);
        viewCadastroPartido.setVisible(true);
    }//GEN-LAST:event_btnCadastrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarRemover;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tblLegendas;
    // End of variables declaration//GEN-END:variables
}
